/**
 * generate-content.js
 * Reads every README.md and notes.md from topics/regex/concepts/
 * and writes docs/js/content.js with all content embedded as a
 * single JavaScript constant.
 *
 * Run once before building:  node generate-content.js
 * Or add to package.json:   "prebuild": "node generate-content.js"
 */

const fs   = require('fs');
const path = require('path');

const conceptsDir = path.join(__dirname, 'topics', 'regex', 'concepts');
const outputFile  = path.join(__dirname, 'docs', 'js', 'content.js');

const concepts = fs.readdirSync(conceptsDir)
  .filter(d => fs.statSync(path.join(conceptsDir, d)).isDirectory())
  .sort();

const content = {};

for (const concept of concepts) {
  content[concept] = {};
  for (const [key, filename] of [['readme', 'README.md'], ['notes', 'notes.md']]) {
    const filePath = path.join(conceptsDir, concept, filename);
    try {
      content[concept][key] = fs.readFileSync(filePath, 'utf8');
      console.log(`  ✓ ${concept}/${filename}`);
    } catch (_) {
      content[concept][key] = `# ${filename} not found`;
      console.warn(`  ✗ ${concept}/${filename} — missing`);
    }
  }
}

const js = `// Auto-generated by generate-content.js — do not edit manually.
// Regenerate with: node generate-content.js
const CONTENT = ${JSON.stringify(content)};
`;

fs.writeFileSync(outputFile, js, 'utf8');
console.log(`\nWrote ${outputFile} (${(Buffer.byteLength(js) / 1024).toFixed(0)} KB, ${concepts.length} concepts)`);
